CREATE MEMORY TABLE PUBLIC.CLASSE(ID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,NUMERO VARCHAR(255) NOT NULL,LIBELLE VARCHAR(255) NOT NULL,UTILISABLE CHARACTER(1))
ALTER TABLE PUBLIC.CLASSE ALTER COLUMN ID RESTART WITH 10

insert into classe    values ('2', 'Comptes d\'immobilisations')
insert into classe    values ('3', 'Comptes de stocks et en-cours')
insert into classe    values ('4', 'Comptes de tiers')
insert into classe    values ('5', 'Comptes financiers')
insert into classe    values (''6', 'Comptes de charges')
insert into classe    values (', '7','Comptes de produits')
insert into classe    values ('8', 'Comptes spéciaux')
insert into classe    values ('9', 'Comptes analytiques d\'exploitation')
